Refactor `Subscriber::RemotePublisherConn` into a `Subscription` struct
team-rocos/rosgo pull request #16
Opened 2020-12-29 02:44 UTC by hoani

`Subscriber` has a go routine called `startRemotePublisherConn` which is responsible for:
- establishing a connection with a publisher on a specific topic
- packetising incoming data
- handling errors
- Attempting to recover from recoverable states

In order to place flow control at the root of the agent's subscriptions; this part of the code has been refactored so that:
- the flow control feature can be implemented safely without inadvertently breaking functionality
- the performance of the subscription can be monitored (so we know we at least aren't making it worse) 

### Improvements
- breaks `startRemotePublisherConn` out into a `Subscription` object
  - Serious amount of unit tests
- removes a couple of nasty bugs
  - previous code didn't take into account that `int` is 32-bit for a bunch of embedded linux systems; this means that the `int(msgSize) < 256000000` filter will still let quite a few very large (up to 4GB) packets be created (since these will become negative numbers on the cast... so they will pass the size limit!)
  - Fixed the `conn` object not actually getting closed when the `quitChan` channel is called
- Some performance improvement by using a pooled buffer rather than allocating new buffers every time a new message is received:
```
hoani@rocos-mint-vm:~/git/rosgo/ros (improvement/refactorSubscription)
└─ $ ▶ go test -bench . 
goos: linux
goarch: amd64
pkg: github.com/team-rocos/rosgo/ros
BenchmarkRemotePublisherConn_Throughput1Kb-2
   70639             14819 ns/op
BenchmarkRemotePublisherConn_NewThroughput1Kb-2       
   84954             13763 ns/op
BenchmarkRemotePublisherConn_Throughput1Mb-2
    3025            389229 ns/op
BenchmarkRemotePublisherConn_NewThroughput1Mb-2
    6218            187738 ns/op
PASS
ok      github.com/team-rocos/rosgo/ros 9.057s
``` 

### Concerns

This MR was written to be a light touch on the rosgo code; however there are some race-conditions/vulnerabilities in the current implementation; namely:
- The 1 second timeout waiting for a read is too long, we should consider reading chunks of the payload and allowing the timeout to extend everytime we do this so that the timeout period is reasonable
- Read operations are race conditions, if a timeout triggers halfway through a write, then we lose a partial buffer and then have to disconnect/reconnect to a publisher in order to synchronize. This recovery mechanism is good; however, the reading could be done better so that we don't have this race condition

2021-01-08 01:12 UTC, edwinhayes requested changes
There are a few things you note as outstanding: can you please create corresponding child tickets under the ROCOS-2385 epic to ensure these don't get forgotten about?

2021-01-08 01:12 UTC, edwinhayes commented on ros/subscription.go
> +		defer conn.Close() // Make sure we close this
Don't `defer` inside a loop like this; non-obvious what the behaviour will be, results in connections being left open unnecessarily, and can lead to weird bugs.

2021-01-11 21:52 UTC, hoani commented on ros/subscription.go
> +		defer conn.Close() // Make sure we close this
Good point, I'll look into a few patterns for managing this better

2021-01-13 01:44 UTC, hoani commented on ros/subscriber_benchmark_test.go
> +	modular "github.com/edwinhayes/logrus-modular"
I would like to defer updating `logrus-modular` since many of rosgo libraries depend directly on the interface defined in `github.com/edwinhayes/logrus-modular`.

Have created a ticket for getting things the fork merged: https://rocosglobal.atlassian.net/browse/ROCOS-2435

Also created https://rocosglobal.atlassian.net/browse/ROCOS-2433 to capture the current state of logrus usage in rosgo and rocos-agent.

2021-01-13 03:18 UTC, hoani commented on ros/subscription.go
> +func newDefaultSubscription(logger *modular.ModuleLogger,
Definitely agree when the `new` function just moved data into a struct.

I took another look at this; the value this function provides is providing some default values to fields which aren't included in the `new` function. I think this might be a better pattern than making the user of the struct determine how to populate these other fields? 

Let me know what you think

2021-01-13 21:26 UTC, edwinhayes commented on ros/subscription.go
> +func newDefaultSubscription(logger *modular.ModuleLogger,
I'm confused by what you mean by this sorry.

`newDefaultSubscription` takes fewer arguments than there are fields in the Subscription struct, but doesn't still is not helpful, because the function is only initialising the fields which don't have arguments to the nil value anyway (unlike C, in Go uninitialised fields are always the nil value, never garbage).

The function only becomes useful if there are some fields which need to be initialised to non-nil values in order for the struct to be valid.

2021-01-19 21:55 UTC, edwinhayes approved these changes
LGTM.

2021-01-19 21:55 UTC, edwinhayes commented on ros/subscription.go
> +// newDefaultSubscription populates a subscription struct from the instantiation fields and fills in default data for the operational fields.
This function still does nothing.

2021-01-19 21:55 UTC, merged