Rocos 2385 dynamic message deserialize
team-rocos/rosgo pull request #19
Opened 2021-01-07 02:53 UTC by hoani

This PR is one of a few PRs created to reduce the load of the agent caused by telemetry.

Several benchmarks have been performed on these changes; and cpu profiling has shown that the load of DynamicMessage::Deserialize for the `map_repeated` topic using a test bag file was reduced from 35% to under 5% of the processing load. This PR removes Deserialize as a primary bottle neck for the agent - more details below.

## Changes

* Efficiency gains!
  * Array deserialization saw between 10 to 500x improvement for deserializing 1Mbyte data
    * Roughly 2x improvement due to using fixed allocation rather than appending to dynamically sized arrays
    * Roughly 2x improvement due to removing iterative binary searches on array definitions where we already knew the type
    * Roughly 3x improvement by removing reflection on each element update - this basically means the go runtime doesn't have to say "is this safe?" every time we add an element to an array which type we already know
    * Additional optimizations made on a per-type basis
  * Nested messages 2-3x improvement
    * Make message types hold the types of their nested messages
      * This prevents us from creating new structs whenever we deserialize
      * MsgTypes are expected to have much longer lifetimes that message structs, so it makes sense they generate and hold this data  
    * Don't generate zero data for nested messages
  * NewMessage improvements
    * Remove dynamic array creation, just make a sized array
* Reliability
  * Add tests for most deserialize cases
  * Add benchmarks to compare changes to deserialize going forward

## Benchmarking

Benchmarks on this PR is complicated since there are a lot of use cases, so I made a report: [Benchmarking Deserialize.pdf](https://github.com/team-rocos/rosgo/files/5779244/Benchmarking.Deserialize.pdf)

The general take away is that performance either improved or stayed the same. In some cases (mostly arrays) it improved alot

## Performance Testing

2021-01-08 02:50 UTC, edwinhayes requested changes

2021-01-08 02:50 UTC, edwinhayes commented on ros/dynamic_message.go
> +	nested map[string]*DynamicMessageType
Is this ok in the case of a message with a recursive definition?  Such as a message which contains a dynamic array of itself.

2021-01-08 02:50 UTC, edwinhayes commented on ros/dynamic_message.go
> +	m.nested = make(map[string]*DynamicMessageType)
Minor thing unrelated to your change; looks like we're returning `m` by value?  That's potentially not ideal, depending on where this is being called from.  Maybe just check that?

2021-01-08 02:50 UTC, edwinhayes commented on ros/dynamic_message.go
> +					err = errors.New("Nested message type not known!")
`err = errors.New("unknown nested message type")`

2021-01-08 02:50 UTC, edwinhayes commented on ros/dynamic_message.go
> +//
Can we move these decode helpers into their own file, since this one is getting pretty huge.

2021-01-08 02:50 UTC, edwinhayes commented on ros/dynamic_message.go
> +		} else { // mot array
sp: not

2021-01-19 21:37 UTC, hoani commented on ros/dynamic_message.go
> +	m.nested = make(map[string]*DynamicMessageType)
In `newDynamicMessageTypeNested` we will now return a pointer.
However, `NewDynamicMessageTypeLiteral` is still a little odd - I've created a ticket [ROCOS-2474](https://rocosglobal.atlassian.net/browse/ROCOS-2474) to address removing this (probably at a time if/when we want to work on `dynamic_action.go`)

2021-01-20 05:25 UTC, hoani commented on ros/dynamic_message.go
> +	nested map[string]*DynamicMessageType
I have added protection for this, see `TestDynamicMessage_TypeWithRecursion` and `TestDynamicMessage_TypeWithBuriedRecursion`

Currently we return error, because I haven't seen anything in ROS spec which indicates messages should be able to do this. 

The solution is that parents pass the `nested` map down, so that the entire tree has a flattened type map; we then return err when attempting to create types that are already in the map. I'm pretty sure this same scheme would be the correct way to handle recursion if we decided we wanted to support recursive types.

2021-01-20 05:25 UTC, hoani commented on ros/dynamic_message.go
> +//
Done!

2021-01-20 05:47 UTC, edwinhayes approved these changes
LGTM.

2021-01-20 05:47 UTC, merged