ch8527 - Test Reporting in Azure Pipelines
team-rocos/rosgo pull request #40
Opened 2021-08-03 23:48 UTC by hoani

Related to [Rocos-Agent PR 653](https://github.com/team-rocos/rocos-agent/pull/653)

Adds test reporting to Azure dev-ops for rosgo - includes test results and code coverage

## Changes

* Add `azure-pipelines.yml` config
* Remove github actions config

## Reporting

* Can now see in depth statistics on Azure pipelines
  * Note - 89% passed, because we need a ROS environment to run all of our tests - some have been skipped. 

![image](https://user-images.githubusercontent.com/4222666/128100019-7e23f907-1a57-46b4-9684-bd8d957d0653.png)

2021-08-03 23:58 UTC, edwinhayes requested changes

2021-08-03 23:58 UTC, edwinhayes commented on libgengo/libgengo_test.go
> +package libgengo
If you create empty files like this, please add a comment so that it's clear that it's supposed to be like this and hasn't been accidentally truncated.
<img width="741" alt="Screen Shot 2021-08-04 at 11 57 41" src="https://user-images.githubusercontent.com/15720644/128100894-79755cd6-13a0-4486-abc4-da499a16399b.png">

2021-08-04 02:00 UTC, hoani commented on libgengo/libgengo_test.go
> +package libgengo
Sweet, done!

2021-08-04 02:20 UTC, edwinhayes approved these changes
LGTM.

2021-08-04 02:20 UTC, merged