[ch12789] - Allow adjusting Master API timeout using to a node 'special' parameter.
team-rocos/rosgo pull request #44
Opened 2022-06-02 04:07 UTC by edwinhayes

2022-06-06 22:30 UTC, mohsenpashna requested changes
A couple of lines left commented, and a question on using MustCompile.

2022-06-06 22:30 UTC, mohsenpashna commented on libgengo/context.go
> +	//components := strings.Split(text, "---")
Do you leave this line commented here?

2022-06-06 22:30 UTC, mohsenpashna commented on libgengo/context.go
> +	rex := regexp.MustCompile("[-]{3,}")
MustCompile panics instead of returning an error: https://gobyexample.com/regular-expressions

Is this an intended behaviour?

2022-06-06 22:30 UTC, mohsenpashna commented on libgengo/context.go
> +	//components := strings.Split(text, "---")
^

2022-06-06 22:51 UTC, edwinhayes commented on libgengo/context.go
> +	rex := regexp.MustCompile("[-]{3,}")
Yes; because it's compiling a literal, it either panics during testing, or never panics.

2022-06-06 22:54 UTC, edwinhayes commented on libgengo/context.go
> +	//components := strings.Split(text, "---")
Removed.

2022-06-06 22:54 UTC, edwinhayes commented on libgengo/context.go
> +	//components := strings.Split(text, "---")
Removed.

2022-06-12 21:59 UTC, mohsenpashna approved these changes
LGTM!

2022-06-12 22:00 UTC, merged